# ================================
# PROD PROFILE
# ================================
app.environment=Production
app.debug=false
app.max-retries=3

# Database (Real MySQL for prod)
db.host=prod-server.myapp.com
db.port=3306
db.name=springdb_prod
db.password=superSecureProdPass123
db.max-connections=50

# Email (Real SMTP for prod)
email.host=smtp.gmail.com
email.port=587
email.username=noreply@myapp.com
email.from=noreply@myapp.com
email.max-emails-per-day=10000

# Logging
logging.level.com.towhid=WARN