spring.application.name=spring-learning

# ================================
# COMMON CONFIG (all environments)
# ================================
# Application Info
app.name=Spring Learning App
app.version=1.0.0
app.author=Towhid

# Settings
app.max-retries=3
app.timeout=5000
app.debug=true

# Custom Message
app.welcome-message=Welcome to Spring Boot!

db.host=localhost
db.port=3306
db.name=springdb
db.max-connections=10
db.password=secret123

email.host=smtp.gmail.com
email.port=587
email.username=towhid@gmail.com
email.password=emailpass123
email.from=noreply@towhid.com
email.max-emails-per-day=100

# Which profile to use
# Change this to switch environments!
spring.profiles.active=dev
