# ================================
# DEV PROFILE
# ================================
app.environment=Development
app.debug=true
app.max-retries=5

# Database (H2 in-memory for dev)
db.host=localhost
db.port=3306
db.name=springdb_dev
db.password=devpass
db.max-connections=5

# Email (fake for dev)
email.host=localhost
email.port=1025
email.username=dev@localhost.com
email.from=dev@localhost.com
email.max-emails-per-day=10

# Logging
logging.level.com.towhid=DEBUG