# ================================
# TEST PROFILE
# ================================
app.environment=Testing
app.debug=true
app.max-retries=1

# Database (separate test DB)
db.host=localhost
db.port=3306
db.name=springdb_test
db.password=testpass
db.max-connections=2

# Email (fake for testing)
email.host=localhost
email.port=1025
email.username=test@localhost.com
email.from=test@localhost.com
email.max-emails-per-day=5

# Logging
logging.level.com.towhid=DEBUG