package com.towhid.spring_data.day06.jdbc.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// @Data = generates getters, setters,
//         toString, equals, hashCode
// @AllArgsConstructor = constructor with all fields
// @NoArgsConstructor  = empty constructor
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Student {

    private Integer id;
    // INT in DB → Integer in Java
    // Integer (not int) because it can be null
    // when we create a new student before saving

    private String name;
    private String email;
    private Integer age;
    private String course;
    private Double grade;
    // Double (not double) → can be null

    // Constructor without id
    // Used when CREATING a new student
    // (id will be auto-generated by MySQL)
    public Student(String name, String email,
                   Integer age, String course, Double grade) {
        this.name = name;
        this.email = email;
        this.age = age;
        this.course = course;
        this.grade = grade;
    }
}